"
I represent Fortran Arithmetic Complex Literal (Constant) statement
"
Class {
	#name : #FASTEsopeComplexLiteral,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTNumericalLiteral',
	#classTraits : 'FASTEsopeTNumericalLiteral classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeComplexLiteral class >> annotation [

	<FMClass: #ComplexLiteral super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
