"
I represent Fortran Arithmetic Real Literal (Constant) statement
"
Class {
	#name : #FASTEsopeRealLiteral,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTNumericalLiteral',
	#classTraits : 'FASTEsopeTNumericalLiteral classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeRealLiteral class >> annotation [

	<FMClass: #RealLiteral super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
