"
I represent Fortran Character Literal (Constant) statement
"
Class {
	#name : #FASTEsopeCharacterLiteral,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTCharacterLiteral',
	#classTraits : 'FASTEsopeTCharacterLiteral classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeCharacterLiteral class >> annotation [

	<FMClass: #CharacterLiteral super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
