"
I represent Fortran Structure statement
"
Class {
	#name : #FASTEsopeStructure,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTExpression',
	#classTraits : 'FASTEsopeTExpression classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeStructure class >> annotation [

	<FMClass: #Structure super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
