"
I represent Fortran Intrinsic statement
"
Class {
	#name : #FASTEsopeIntrinsicStatement,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTLabelledStatement',
	#classTraits : 'FASTEsopeTLabelledStatement classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeIntrinsicStatement class >> annotation [

	<FMClass: #IntrinsicStatement super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
