"
I represent Fortran Pointer statement
"
Class {
	#name : #FASTEsopePointer,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTExpression',
	#classTraits : 'FASTEsopeTExpression classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopePointer class >> annotation [

	<FMClass: #Pointer super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
