"
I represent Fortran Arithmetic Integer Literal (Constant) statement
"
Class {
	#name : #FASTEsopeIntegerLiteral,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTNumericalLiteral',
	#classTraits : 'FASTEsopeTNumericalLiteral classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeIntegerLiteral class >> annotation [

	<FMClass: #IntegerLiteral super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
