"
I represent a Fortran Function
"
Class {
	#name : #FASTEsopeFunction,
	#superclass : #FASTEsopeProcedure,
	#traits : 'FASTEsopeTWithParameters',
	#classTraits : 'FASTEsopeTWithParameters classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeFunction class >> annotation [

	<FMClass: #Function super: #FASTEsopeProcedure>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
