"
I represent Fortran Substring
"
Class {
	#name : #FASTEsopeSubstring,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTExpression',
	#classTraits : 'FASTEsopeTExpression classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeSubstring class >> annotation [

	<FMClass: #Substring super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
