"
I represent Fortran Record statement
"
Class {
	#name : #FASTEsopeRecord,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTExpression',
	#classTraits : 'FASTEsopeTExpression classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeRecord class >> annotation [

	<FMClass: #Record super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
