"
I represent Fortran If (Arithmetic) statement
"
Class {
	#name : #FASTEsopeIfArithmeticStatement,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTLabelledStatement',
	#classTraits : 'FASTEsopeTLabelledStatement classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeIfArithmeticStatement class >> annotation [

	<FMClass: #IfArithmeticStatement super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
