"
I represent Fortran Go To (Computed) statement
"
Class {
	#name : #FASTEsopeGoToComputedStatement,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTLabelledStatement',
	#classTraits : 'FASTEsopeTLabelledStatement classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeGoToComputedStatement class >> annotation [

	<FMClass: #GoToComputedStatement super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
