"
The BLOCK DATA statement identifies a subprogram that initializes variables and arrays in labeled common blocks.
"
Class {
	#name : #FASTEsopeBlockData,
	#superclass : #FASTEsopeSubprogram,
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeBlockData class >> annotation [

	<FMClass: #BlockData super: #FASTEsopeSubprogram>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
