"
I represent Fortran Arithmetic Double Precision Literal (Constant) statement
"
Class {
	#name : #FASTEsopeDoublePrecisionLiteral,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTNumericalLiteral',
	#classTraits : 'FASTEsopeTNumericalLiteral classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeDoublePrecisionLiteral class >> annotation [

	<FMClass: #DoublePrecisionLiteral super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
