"
I represent a fortran statement with a label
"
Trait {
	#name : #FASTEsopeTLabelledStatement,
	#traits : 'FASTEsopeTStatement',
	#classTraits : 'FASTEsopeTStatement classTrait',
	#category : #'FAST-Esope-Entities-Traits'
}

{ #category : #meta }
FASTEsopeTLabelledStatement classSide >> annotation [

	<FMClass: #TLabelledStatement super: #Object>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
