"
I represent Fortran Go To (Unconditional) statement
"
Class {
	#name : #FASTEsopeGoToUnconditionalStatement,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTLabelledStatement',
	#classTraits : 'FASTEsopeTLabelledStatement classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeGoToUnconditionalStatement class >> annotation [

	<FMClass: #GoToUnconditionalStatement super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
