"
I represent Fortran Boolean Literal (Constant) statement
"
Class {
	#name : #FASTEsopeBooleanLiteral,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTBooleanLiteral',
	#classTraits : 'FASTEsopeTBooleanLiteral classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeBooleanLiteral class >> annotation [

	<FMClass: #BooleanLiteral super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
