"
I represent Fortran Arithmetic Double Complex Literal (Constant) statement
"
Class {
	#name : #FASTEsopeDoubleComplexLiteral,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTNumericalLiteral',
	#classTraits : 'FASTEsopeTNumericalLiteral classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeDoubleComplexLiteral class >> annotation [

	<FMClass: #DoubleComplexLiteral super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
