"
I represent Fortran Go To( Assigned) statement
"
Class {
	#name : #FASTEsopeGoToAssignedStatement,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTLabelledStatement',
	#classTraits : 'FASTEsopeTLabelledStatement classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeGoToAssignedStatement class >> annotation [

	<FMClass: #GoToAssignedStatement super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
