"
I represent an Ampersand Character Literal (Constant) that is often used in parameters and format identifiers
"
Class {
	#name : #FASTEsopeAmpersand,
	#superclass : #FASTEsopeEntity,
	#traits : 'FASTEsopeTCharacterLiteral',
	#classTraits : 'FASTEsopeTCharacterLiteral classTrait',
	#category : #'FAST-Esope-Entities-Entities'
}

{ #category : #meta }
FASTEsopeAmpersand class >> annotation [

	<FMClass: #Ampersand super: #FASTEsopeEntity>
	<package: #'FAST-Esope-Entities'>
	<generated>
	^ self
]
